# Generated by Django 4.2.7 on 2023-12-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='from_to',
            new_name='from_type',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='nationality',
            new_name='nationality_type',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('name', 'video_type', 'from_type', 'nationality_type')},
        ),
    ]
